/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.login_registrazione_design;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author ildon
 */
public class Verifica_email extends javax.swing.JFrame {

    /**
     * Creates new form Verifica_email
     */
    public Verifica_email() {
        initComponents();
        
        
         //centrare il modulo
        this.setLocationRelativeTo(null);
        
        //creo il bordo verde per il pannello del titolo
       
        Border jpanel_titolo_bordo = BorderFactory.createMatteBorder(0, 2, 2, 2, Color.decode("#276F08"));
        jPanel_titolo1.setBorder(jpanel_titolo_bordo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField_codice = new javax.swing.JTextField();
        jButton_verifica = new javax.swing.JButton();
        jLabel_Create_Account = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        riprovainvio = new javax.swing.JLabel();
        jLabel_minimizza = new javax.swing.JLabel();
        jLabel_chiudi = new javax.swing.JLabel();
        jPanel_titolo1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Logo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTextField_codice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_codice.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_codice.setText("codice");
        jTextField_codice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_codiceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_codiceFocusLost(evt);
            }
        });
        jTextField_codice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codiceActionPerformed(evt);
            }
        });
        jTextField_codice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_codiceKeyPressed(evt);
            }
        });

        jButton_verifica.setBackground(new java.awt.Color(0, 75, 56));
        jButton_verifica.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jButton_verifica.setForeground(new java.awt.Color(255, 255, 255));
        jButton_verifica.setText("Verifica");
        jButton_verifica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_verifica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_verifica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_verificaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_verificaMouseExited(evt);
            }
        });
        jButton_verifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_verificaActionPerformed(evt);
            }
        });

        jLabel_Create_Account.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Create_Account.setForeground(new java.awt.Color(0, 102, 0));
        jLabel_Create_Account.setText(">>Problemi di accesso? torna alla registrazione");
        jLabel_Create_Account.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Create_Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Create_AccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Create_AccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Create_AccountMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Inserisci il codice ricevuto via email");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("OPPURE");

        riprovainvio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        riprovainvio.setForeground(new java.awt.Color(0, 102, 0));
        riprovainvio.setText(">>Riprova l'invio del codice");
        riprovainvio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        riprovainvio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riprovainvioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                riprovainvioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                riprovainvioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel_Create_Account))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jTextField_codice, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButton_verifica, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(riprovainvio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addComponent(jTextField_codice, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jButton_verifica, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Create_Account)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(riprovainvio)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jLabel_minimizza.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_minimizza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimizza.setText("-");
        jLabel_minimizza.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_minimizza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimizza.setMinimumSize(new java.awt.Dimension(8, 22));
        jLabel_minimizza.setPreferredSize(new java.awt.Dimension(22, 22));
        jLabel_minimizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizzaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizzaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_minimizzaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel_minimizzaMouseReleased(evt);
            }
        });

        jLabel_chiudi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_chiudi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_chiudi.setText("x");
        jLabel_chiudi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_chiudi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_chiudi.setPreferredSize(new java.awt.Dimension(22, 22));
        jLabel_chiudi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_chiudiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_chiudiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel_chiudiMouseReleased(evt);
            }
        });

        jPanel_titolo1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 38)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Verifica email");

        javax.swing.GroupLayout jPanel_titolo1Layout = new javax.swing.GroupLayout(jPanel_titolo1);
        jPanel_titolo1.setLayout(jPanel_titolo1Layout);
        jPanel_titolo1Layout.setHorizontalGroup(
            jPanel_titolo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titolo1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(16, 16, 16))
        );
        jPanel_titolo1Layout.setVerticalGroup(
            jPanel_titolo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titolo1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Harlow Solid Italic", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("il paroliere");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jPanel_titolo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(jLabel_minimizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_chiudi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_titolo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_minimizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_chiudi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_codiceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_codiceFocusGained

        // cancella testo di default
        if(jTextField_codice.getText().trim().toLowerCase().equals("codice")){
            jTextField_codice.setText("");
            jTextField_codice.setForeground(Color.black);
        }
        

    }//GEN-LAST:event_jTextField_codiceFocusGained

    private void jTextField_codiceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_codiceFocusLost
        //se il testo è vuoto o uguale a username allora setta username
        if(jTextField_codice.getText().trim().equals("") || jTextField_codice.getText().trim().toLowerCase().equals("codice")){
            jTextField_codice.setText("codice");
            jTextField_codice.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_jTextField_codiceFocusLost

    private void jButton_verificaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_verificaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_verificaMouseEntered

    private void jButton_verificaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_verificaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_verificaMouseExited

    private void jButton_verificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_verificaActionPerformed

        PreparedStatement st;
        ResultSet rs;
        PreparedStatement st1;
        //ottieni username e password
        try{
        int codice = Integer.parseInt(jTextField_codice.getText());
        
        //crea una select query per verificare se l'utente esiste
        String query ="SELECT * FROM playerip WHERE codice = ? AND stato = '0'";
        String query1="UPDATE playerip SET stato = '1'";

        if(codice == 0){
            JOptionPane.showMessageDialog(null, "Inserire codice", "codice vuoto", 2);
        }
        else{

            try {
                st = Connessione_db.getConnection().prepareStatement(query);

                st.setInt(1, codice);
                
                rs = st.executeQuery();

                if(rs.next()){
                    st1 = Connessione_db.getConnection().prepareStatement(query1);
                    int i = st1.executeUpdate();
                    //visualizza un nuovo modulo
                    Paroliere_Form form = new Paroliere_Form();
                    form.setVisible(true);
                    form.pack();
                    form.setLocationRelativeTo(null);
                    //chiudi il modulo di login
                    this.dispose();

                }
                else{
                    //messaggio di errore
                    JOptionPane.showMessageDialog(null, "codice non valido","errore di login",2);
                }

            } catch (SQLException ex) {
                Logger.getLogger(Login_Modulo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
        catch(NumberFormatException exn){
        JOptionPane.showMessageDialog(null, "Inserire codice valido", "codice non valido", 2);   
       }

    }//GEN-LAST:event_jButton_verificaActionPerformed

    private void jLabel_Create_AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Create_AccountMouseClicked

        Registrazione_modulo rf = new Registrazione_modulo();
        rf.setVisible(true);
        rf.pack();
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jLabel_Create_AccountMouseClicked

    private void jLabel_Create_AccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Create_AccountMouseEntered
        Border label_border =BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("#276F08"));
        jLabel_Create_Account.setBorder(label_border);
    }//GEN-LAST:event_jLabel_Create_AccountMouseEntered

    private void jLabel_Create_AccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Create_AccountMouseExited
        jLabel_Create_Account.setBorder(null);
    }//GEN-LAST:event_jLabel_Create_AccountMouseExited

    private void jLabel_minimizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizzaMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizzaMouseClicked

    private void jLabel_minimizzaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizzaMouseEntered

    }//GEN-LAST:event_jLabel_minimizzaMouseEntered

    private void jLabel_minimizzaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizzaMousePressed
        jLabel_minimizza.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.EtchedBorder.LOWERED));
    }//GEN-LAST:event_jLabel_minimizzaMousePressed

    private void jLabel_minimizzaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizzaMouseReleased
        jLabel_minimizza.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.EtchedBorder.RAISED));
    }//GEN-LAST:event_jLabel_minimizzaMouseReleased

    private void jLabel_chiudiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_chiudiMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_chiudiMouseClicked

    private void jLabel_chiudiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_chiudiMousePressed
        jLabel_chiudi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.EtchedBorder.LOWERED));
    }//GEN-LAST:event_jLabel_chiudiMousePressed

    private void jLabel_chiudiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_chiudiMouseReleased
        jLabel_chiudi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.EtchedBorder.RAISED));
    }//GEN-LAST:event_jLabel_chiudiMouseReleased

    private void jTextField_codiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_codiceActionPerformed

    private void jTextField_codiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_codiceKeyPressed
         
    }//GEN-LAST:event_jTextField_codiceKeyPressed

    private void riprovainvioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riprovainvioMouseEntered
        Border label_border =BorderFactory.createMatteBorder(0, 0, 1, 0, Color.decode("#276F08"));
        riprovainvio.setBorder(label_border);
    }//GEN-LAST:event_riprovainvioMouseEntered

    private void riprovainvioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riprovainvioMouseExited
        riprovainvio.setBorder(null);
    }//GEN-LAST:event_riprovainvioMouseExited

    private void riprovainvioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riprovainvioMouseClicked
        InvioNuovoCodice inc = new InvioNuovoCodice();
        inc.setVisible(true);
        inc.pack();
        inc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_riprovainvioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verifica_email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verifica_email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verifica_email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verifica_email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verifica_email().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo2;
    private javax.swing.JButton jButton_verifica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Create_Account;
    private javax.swing.JLabel jLabel_chiudi;
    private javax.swing.JLabel jLabel_minimizza;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_titolo1;
    private javax.swing.JTextField jTextField_codice;
    private javax.swing.JLabel riprovainvio;
    // End of variables declaration//GEN-END:variables
}
